In [1]:
import os
os.getcwd

In [2]:
import pandas as pd
#Load the CSV WITHOUT skipping anything
# This lets us inspect the raw file and find the real header row.
raw = pd.read_csv(
    r"/Users/harimagar/Documents/PROJECTS/hospital-readmission-ml-and-nhs-ae-dashboard/data/ae_raw/nhs.csv",
    header=None
)

raw.head(40)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Title:,A&E Attendances & Emergency Admission monthly ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Summary:,"A&E attendances, performance and emergency adm...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Period:,March 2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Source:,SDCS data collection - MSitAE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Basis:,Provider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Published:,16th April 2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Revised:,14th May 2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Status:,Published,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Contact:,Kerry Evert - england.aedata@nhs.net,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,System Level Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,A&E attendances,NaN,NaN,NaN,A&E attendances < 4 hours from arrival to admi...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Code,System,Type 1 Departments - Major A&E,Type 2 Departments - Single Specialty,Type 3 Departments - Other A&E/Minor Injury Unit,Total attendances,Type 1 Departments - Major A&E,Type 2 Departments - Single Specialty,Type 3 Departments - Other A&E/Minor Injury Unit,Total Attendances < 4 hours,...,Emergency Admissions via Type 2 A&E,Emergency Admissions via Type 3 and 4 A&E,Total Emergency Admissions via A&E,Other Emergency admissions (i.e not via A&E),Total Emergency Admissions,Number of patients spending >4 hours from deci...,Number of patients spending >12 hours from dec...,NaN,NaN,NaN
16,-,-,"1,478,144","55,393","898,735","2,432,272","947,365","53,329","874,867","1,875,561",...,"1,423","6,226","410,005","143,887","553,892","123,870","46,665",NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,QOX,"NHS Bath And North East Somerset, Swindon And ...","20,771",377,"12,448","33,596","11,678",377,"11,857","23,912",...,0,11,"7,293","4,480","11,773","2,567",668,NaN,NaN,NaN
19,QHG,"NHS Bedfordshire, Luton And Milton Keynes Inte...","26,816",0,"18,199","45,015","18,375",0,"18,106","36,481",...,0,0,"7,954","2,938","10,892",698,15,NaN,NaN,NaN
20,QHL,NHS Birmingham And Solihull Integrated Care Board,"39,752",423,"14,808","54,983","24,886",423,"14,782","40,091",...,0,0,"11,406","7,843","19,249","4,425","1,513",NaN,NaN,NaN
21,QUY,"NHS Bristol, North Somerset And South Gloucest...","26,384","2,625","9,347","38,356","16,658","2,379","9,027","28,064",...,11,0,"8,238","4,078","12,316","2,666","1,105",NaN,NaN,NaN
22,QU9,"NHS Buckinghamshire, Oxfordshire And Berkshire...","36,610","5,549","15,460","57,619","25,561","5,518","15,178","46,257",...,974,58,"12,283","5,986","18,269","1,274",282,NaN,NaN,NaN
23,QUE,NHS Cambridgeshire And Peterborough Integrated...,"28,164",0,"11,428","39,592","17,338",0,"11,114","28,452",...,0,79,"7,242","1,879","9,121","2,310","1,349",NaN,NaN,NaN
24,QYG,NHS Cheshire And Merseyside Integrated Care Board,"74,941","3,578","51,120","129,639","42,894","3,377","49,386","95,657",...,122,0,"24,077","8,121","32,198","8,326","5,004",NaN,NaN,NaN
25,QT6,NHS Cornwall And The Isles Of Scilly Integrate...,"6,938",0,"12,626","19,564","3,547",0,"12,025","15,572",...,0,52,"2,393","1,579","3,972",985,467,NaN,NaN,NaN
26,QWU,NHS Coventry And Warwickshire Integrated Care ...,"29,411","2,667","8,627","40,705","21,746","2,574","8,446","32,766",...,40,50,"4,128","1,040","5,168",866,235,NaN,NaN,NaN
27,QHM,NHS North East And North Cumbria Integrated Ca...,"76,255","3,272","75,214","154,741","47,237","3,163","74,301","124,701",...,45,894,"26,938","11,572","38,510","4,117",376,NaN,NaN,NaN
28,QJK,NHS Devon Integrated Care Board,"31,474",174,"18,529","50,177","16,444",160,"18,352","34,956",...,0,0,"8,942","5,183","14,125","2,293",590,NaN,NaN,NaN
29,QVV,NHS Dorset Integrated Care Board,"20,661",0,"8,226","28,887","12,363",0,"8,221","20,584",...,1,0,"6,150","3,127","9,277","1,725",593,NaN,NaN,NaN
30,QMF,NHS North East London Integrated Care Board,"51,367","3,435","41,272","96,074","33,483","3,016","40,007","76,506",...,1,35,"10,200","3,917","14,117","3,656","1,837",NaN,NaN,NaN
31,QNQ,NHS Frimley Integrated Care Board,"23,737","1,013","11,602","36,352","16,182","1,012","11,359","28,553",...,0,0,"6,966",140,"7,106","1,703",637,NaN,NaN,NaN
32,QR1,NHS Gloucestershire Integrated Care Board,"14,347",0,"9,057","23,404","9,264",0,"8,833","18,097",...,0,1,"2,981","3,051","6,032",771,489,NaN,NaN,NaN
33,QOP,NHS Greater Manchester Integrated Care Board,"90,681","3,891","37,172","131,744","57,518","3,753","36,351","97,622",...,168,706,"24,606","6,261","30,867","8,484","2,485",NaN,NaN,NaN
34,QRL,NHS Hampshire And Isle Of Wight Integrated Car...,"40,034","2,745","28,126","70,905","25,526","2,669","27,324","55,519",...,20,62,"12,706","5,428","18,134","2,926","1,121",NaN,NaN,NaN
35,QE1,NHS Lancashire And South Cumbria Integrated Ca...,"43,736",0,"32,821","76,557","28,397",0,"31,695","60,092",...,0,180,"12,389","6,328","18,717","4,950","2,260",NaN,NaN,NaN
36,QGH,NHS Herefordshire And Worcestershire Integrate...,"20,567","1,032","6,323","27,922","12,065","1,032","6,276","19,373",...,0,0,"4,647","1,068","5,715","2,407","1,069",NaN,NaN,NaN
37,QM7,NHS Hertfordshire And West Essex Integrated Ca...,"26,870",0,"23,971","50,841","18,394",0,"23,620","42,014",...,0,3,"9,150","1,393","10,543","1,713",275,NaN,NaN,NaN
38,QOQ,NHS Humber And North Yorkshire Integrated Care...,"38,708",350,"31,412","70,470","22,021",350,"30,144","52,515",...,0,0,"16,421","4,737","21,158","4,106","1,337",NaN,NaN,NaN
39,QJ2,NHS Derby And Derbyshire Integrated Care Board,"29,431",0,"26,609","56,040","16,767",0,"26,001","42,768",...,0,16,"6,322","2,214","8,536","2,296",537,NaN,NaN,NaN

In [3]:
#Automatically detect the header row
# The real header row contains the word "Code".
# This finds the row index where "Code" appears.
header_row = raw[raw.apply(lambda row: row.astype(str).str.contains('Code').any(), axis=1)].index[0]
header_row

15

In [4]:
# skiprows = header_row means Pandas will treat the next row as the header.
df = pd.read_csv(
    r"/Users/harimagar/Documents/PROJECTS/hospital-readmission-ml-and-nhs-ae-dashboard/data/ae_raw/nhs.csv",
    skiprows=header_row
)

In [5]:
df.columns

Index(['Code', 'System', 'Type 1 Departments - Major A&E',
       'Type 2 Departments - Single Specialty',
       'Type 3 Departments - Other A&E/Minor Injury Unit', 'Total attendances',
       'Type 1 Departments - Major A&E.1',
       'Type 2 Departments - Single Specialty.1',
       'Type 3 Departments - Other A&E/Minor Injury Unit.1',
       'Total Attendances < 4 hours', 'Type 1 Departments - Major A&E.2',
       'Type 2 Departments - Single Specialty.2',
       'Type 3 Departments - Other A&E/Minor Injury Unit.2',
       'Total Attendances > 4 hours', 'Percentage in 4 hours or less (all)',
       'Percentage in 4 hours or less (type 1)',
       'Percentage in 4 hours or less (type 2)',
       'Percentage in 4 hours or less (type 3)',
       'Emergency Admissions via Type 1 A&E',
       'Emergency Admissions via Type 2 A&E',
       'Emergency Admissions via Type 3 and 4 A&E',
       'Total Emergency Admissions via A&E',
       'Other Emergency admissions (i.e not via A&E)',
       'Total Emergency Admissions',
       'Number of patients spending >4 hours from decision to admit to admission',
       'Number of patients spending >12 hours from decision to admit to admission',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28'],
      dtype='str')

In [6]:
df = df[~((df['Code'] == '-') & (df['System'] == '-'))]

In [7]:
#Clean numeric columns
# Convert numbers stored as strings with commas into floats.
# If conversion fails (e.g., text columns), we ignore it.
for col in df.columns:
    try:
        df[col] = df[col].astype(str).str.replace(',', '').astype(float)
    except:
        pass

In [8]:
print(df.info())
print(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 375 entries, 1 to 375
Data columns (total 29 columns):
 #   Column                                                                     Non-Null Count  Dtype
---  ------                                                                     --------------  -----
 0   Code                                                                       42 non-null     str
 1   System                                                                     42 non-null     str
 2   Type 1 Departments - Major A&E                                             42 non-null     float64
 3   Type 2 Departments - Single Specialty                                      42 non-null     float64
 4   Type 3 Departments - Other A&E/Minor Injury Unit                           42 non-null     float64
 5   Total attendances                                                          42 non-null     float64
 6   Type 1 Departments - Major A&E.1                                           42 non-null     float64
 7   Type 2 Departments - Single Specialty.1                                    42 non-null     float64
 8   Type 3 Departments - Other A&E/Minor Injury Unit.1                         42 non-null     float64
 9   Total Attendances < 4 hours                                                42 non-null     float64
 10  Type 1 Departments - Major A&E.2                                           42 non-null     float64
 11  Type 2 Departments - Single Specialty.2                                    42 non-null     float64
 12  Type 3 Departments - Other A&E/Minor Injury Unit.2                         42 non-null     float64
 13  Total Attendances > 4 hours                                                42 non-null     float64
 14  Percentage in 4 hours or less (all)                                        42 non-null     str
 15  Percentage in 4 hours or less (type 1)                                     42 non-null     str
 16  Percentage in 4 hours or less (type 2)                                     42 non-null     str
 17  Percentage in 4 hours or less (type 3)                                     42 non-null     str
 18  Emergency Admissions via Type 1 A&E                                        42 non-null     float64
 19  Emergency Admissions via Type 2 A&E                                        42 non-null     float64
 20  Emergency Admissions via Type 3 and 4 A&E                                  42 non-null     float64
 21  Total Emergency Admissions via A&E                                         42 non-null     float64
 22  Other Emergency admissions (i.e not via A&E)                               42 non-null     float64
 23  Total Emergency Admissions                                                 42 non-null     float64
 24  Number of patients spending >4 hours from decision to admit to admission   42 non-null     float64
 25  Number of patients spending >12 hours from decision to admit to admission  42 non-null     float64
 26  Unnamed: 26                                                                0 non-null      float64
 27  Unnamed: 27                                                                0 non-null      float64
 28  Unnamed: 28                                                                0 non-null      float64
dtypes: float64(23), str(6)
memory usage: 85.1 KB
None
  Code                                             System  \
1  NaN                                                NaN
2  QOX  NHS Bath And North East Somerset, Swindon And ...
3  QHG  NHS Bedfordshire, Luton And Milton Keynes Inte...
4  QHL  NHS Birmingham And Solihull Integrated Care Board
5  QUY  NHS Bristol, North Somerset And South Gloucest...

   Type 1 Departments - Major A&E  Type 2 Departments - Single Specialty  \
1                             NaN                                    NaN
2                         20771.0                                  377.0
3                         26816.0                                    0.0
4                         39752.0                                  423.0
5                         26384.0                                 2625.0

   Type 3 Departments - Other A&E/Minor Injury Unit  Total attendances  \
1                                               NaN                NaN
2                                           12448.0            33596.0
3                                           18199.0            45015.0
4                                           14808.0            54983.0
5                                            9347.0            38356.0

   Type 1 Departments - Major A&E.1  Type 2 Departments - Single Specialty.1  \
1                               NaN                                      NaN
2                           11678.0                                    377.0
3                           18375.0                                      0.0
4                           24886.0                                    423.0
5                           16658.0                                   2379.0

   Type 3 Departments - Other A&E/Minor Injury Unit.1  \
1                                                NaN
2                                            11857.0
3                                            18106.0
4                                            14782.0
5                                             9027.0

   Total Attendances < 4 hours  ...  Emergency Admissions via Type 2 A&E  \
1                          NaN  ...                                  NaN
2                      23912.0  ...                                  0.0
3                      36481.0  ...                                  0.0
4                      40091.0  ...                                  0.0
5                      28064.0  ...                                 11.0

   Emergency Admissions via Type 3 and 4 A&E  \
1                                        NaN
2                                       11.0
3                                        0.0
4                                        0.0
5                                        0.0

   Total Emergency Admissions via A&E  \
1                                 NaN
2                              7293.0
3                              7954.0
4                             11406.0
5                              8238.0

   Other Emergency admissions (i.e not via A&E) Total Emergency Admissions  \
1                                           NaN                        NaN
2                                        4480.0                    11773.0
3                                        2938.0                    10892.0
4                                        7843.0                    19249.0
5                                        4078.0                    12316.0

  Number of patients spending >4 hours from decision to admit to admission  \
1                                                NaN
2                                             2567.0
3                                              698.0
4                                             4425.0
5                                             2666.0

  Number of patients spending >12 hours from decision to admit to admission  \
1                                                NaN
2                                              668.0
3                                               15.0
4                                             1513.0
5                                             1105.0

  Unnamed: 26  Unnamed: 27  Unnamed: 28
1         NaN          NaN          NaN
2         NaN          NaN          NaN
3         NaN          NaN          NaN
4         NaN          NaN          NaN
5         NaN          NaN          NaN

[5 rows x 29 columns]

In [9]:
df.isnull().sum()

Code                                                                         333
System                                                                       333
Type 1 Departments - Major A&E                                               333
Type 2 Departments - Single Specialty                                        333
Type 3 Departments - Other A&E/Minor Injury Unit                             333
Total attendances                                                            333
Type 1 Departments - Major A&E.1                                             333
Type 2 Departments - Single Specialty.1                                      333
Type 3 Departments - Other A&E/Minor Injury Unit.1                           333
Total Attendances < 4 hours                                                  333
Type 1 Departments - Major A&E.2                                             333
Type 2 Departments - Single Specialty.2                                      333
Type 3 Departments - Other A&E/Minor Injury Unit.2                           333
Total Attendances > 4 hours                                                  333
Percentage in 4 hours or less (all)                                          333
Percentage in 4 hours or less (type 1)                                       333
Percentage in 4 hours or less (type 2)                                       333
Percentage in 4 hours or less (type 3)                                       333
Emergency Admissions via Type 1 A&E                                          333
Emergency Admissions via Type 2 A&E                                          333
Emergency Admissions via Type 3 and 4 A&E                                    333
Total Emergency Admissions via A&E                                           333
Other Emergency admissions (i.e not via A&E)                                 333
Total Emergency Admissions                                                   333
Number of patients spending >4 hours from decision to admit to admission     333
Number of patients spending >12 hours from decision to admit to admission    333
Unnamed: 26                                                                  375
Unnamed: 27                                                                  375
Unnamed: 28                                                                  375
dtype: int64

In [10]:
df.describe()

,Type 1 Departments - Major A&E,Type 2 Departments - Single Specialty,Type 3 Departments - Other A&E/Minor Injury Unit,Total attendances,Type 1 Departments - Major A&E.1,Type 2 Departments - Single Specialty.1,Type 3 Departments - Other A&E/Minor Injury Unit.1,Total Attendances < 4 hours,Type 1 Departments - Major A&E.2,Type 2 Departments - Single Specialty.2,...,Emergency Admissions via Type 2 A&E,Emergency Admissions via Type 3 and 4 A&E,Total Emergency Admissions via A&E,Other Emergency admissions (i.e not via A&E),Total Emergency Admissions,Number of patients spending >4 hours from decision to admit to admission,Number of patients spending >12 hours from decision to admit to admission,Unnamed: 26,Unnamed: 27,Unnamed: 28
count,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,...,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,42.000000,0.0,0.0,0.0
mean,35193.904762,1318.880952,21398.452381,57911.238095,22556.309524,1269.738095,20830.166667,44656.214286,12637.595238,49.142857,...,33.880952,148.238095,9762.023810,3425.880952,13187.904762,2949.285714,1111.071429,NaN,NaN,NaN
std,18578.948294,1726.958615,14932.953517,32569.518519,12556.425013,1669.991092,14584.098303,26160.385160,6610.143075,89.729559,...,152.118247,351.788171,5619.205657,2493.715508,7675.432734,1801.622768,886.466744,NaN,NaN,NaN
min,6938.000000,0.000000,5840.000000,17286.000000,3547.000000,0.000000,5458.000000,10623.000000,3391.000000,0.000000,...,0.000000,0.000000,2393.000000,140.000000,3972.000000,445.000000,15.000000,NaN,NaN,NaN
25%,22916.500000,0.000000,11457.000000,35292.250000,14347.750000,0.000000,11175.250000,26570.000000,8449.750000,0.000000,...,0.000000,0.000000,6193.000000,1513.750000,7958.500000,1915.500000,550.250000,NaN,NaN,NaN
50%,28967.500000,400.000000,15710.000000,47596.000000,18384.500000,400.000000,14980.000000,35718.500000,10959.500000,0.000000,...,0.000000,7.000000,8549.000000,2716.500000,10965.500000,2406.500000,1056.500000,NaN,NaN,NaN
75%,43715.000000,2527.500000,27746.750000,73777.500000,28575.500000,2343.000000,26993.250000,58948.750000,15122.250000,66.750000,...,1.000000,137.000000,12186.500000,4705.750000,18016.250000,3851.000000,1358.750000,NaN,NaN,NaN
max,90681.000000,6887.000000,75214.000000,154741.000000,57518.000000,6717.000000,74301.000000,124701.000000,33163.000000,419.000000,...,974.000000,1987.000000,26938.000000,11572.000000,38510.000000,8484.000000,5004.000000,NaN,NaN,NaN

In [11]:
df.to_csv("../../data/processed/cleaned_ae_system_level.csv", index=False)

In [12]:
import os
os.listdir()

['01_data_exploration.ipynb']